export const EXAMPLE_REQUEST = "EXAMPLE_REQUEST";
export const EXAMPLE_SUCCESS = "EXAMPLE_SUCCESS";
export const EXAMPLE_ERROR = "EXAMPLE_ERROR";

export const SAVE_TODO_REQUEST = "SAVE_TODO_REQUEST";
export const SAVE_TODO_SUCCESS = "SAVE_TODO_SUCCESS";
export const SAVE_TODO_ERROR = "SAVE_TODO_ERROR";

export const COMPLETED_TODO_REQUEST = "COMPLETED_TODO_REQUEST";
export const COMPLETED_TODO_SUCCESS = "COMPLETED_TODO_SUCCESS";
export const COMPLETED_TODO_ERROR = "COMPLETED_TODO_ERROR";
